---
apiVersion: v1
kind: Namespace
metadata:
  name: ifconfig

---
apiVersion: v1
kind: LimitRange
metadata:
  name: ifconfig
  namespace: ifconfig
spec:
  limits:
  - min:
      cpu: 100m
      memory: 20Mi
    max:
      cpu: 200m
      memory: 100Mi
    type: Container

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ifconfig
  namespace: ifconfig
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 500Mi
    limits.cpu: 1000m
    limits.memory: 1Gi

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-k8s-dns
  namespace: ifconfig
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
