---
name: Tests and checks

on:
  push:
    branches:
      - '*'
      - '!master'
  schedule:
    - cron: '0 1 * * 0'

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.20.7
