---
name: Tests and checks

on:
  push:
    branches:
      - '**'
      - '!master'
    paths-ignore:
      - '.circleci/**'
      - '.github/**'
      - '!.github/workflows/tests-and-checks.yml'
      - '.k8s/**'
      - '.vscode/**'
      - '*.md'
  schedule:
    - cron: '0 1 * * 0'

permissions:
  contents: read

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@3a32958c2706f7048305d5a2e53633d7e37e97d0 # v1
        with:
          go-version-input: 1.22.2

  tests:
    strategy:
      matrix:
        go: [ '~1.21', '~1.22' ]
    runs-on: ubuntu-latest
    name: Run tests with go version ${{ matrix.go }}
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go }}

      - run: go test -v -fuzz FuzzHandler -fuzztime 50x ./handlers/ip/
