---
name: Tests and checks

on:
  push:
    branches:
      - '*'
      - '!master'
  schedule:
    - cron: '0 1 * * 0'

permissions:
  contents: read

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@dd3ead030e4f2cf713062f7a3395191802364e13 # v1
        with:
          go-version-input: 1.20.7
