---
name: Tests and checks

on:
  push:
    branches:
      - '*'
      - '!master'
  schedule:
    - cron: '0 1 * * 0'

permissions:
  contents: read

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@dd3ead030e4f2cf713062f7a3395191802364e13 # v1
        with:
          go-version-input: 1.20.7

  tests:
    strategy:
      matrix:
        go: [ '~1.20', '~1.21' ]
    runs-on: ubuntu-latest
    name: Run tests with go version ${{ matrix.go }}
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go }}

      - run: go test -v -fuzz FuzzHandler -fuzztime 50x ./handlers/ip/
